name: windows
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
      - name: Install deps
        run: zef install --/test PDF::Lite JSON::Fast App::Mi6
      - name: Build
        run: mi6 build
      - name: Tests
        run: prove -e raku -vr t
